using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using static System.Windows.Forms.VisualStyles.VisualStyleElement;
using ListView = System.Windows.Forms.ListView;

namespace trollgen
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            pictureBox1.SizeMode = PictureBoxSizeMode.StretchImage;
            UpdTxt();
        }

        private void textBox1_TextChanged(object sender, EventArgs e)
        {
            pictureBox1.ImageLocation = textBox1.Text;
            UpdTxt();
        }

        private void pictureBox1_Click(object sender, EventArgs e)
        {

        }

        private void richTextBox1_TextChanged(object sender, EventArgs e)
        {
            UpdTxt();
        }
        private void UpdTxt()
        {
            string template = "data:text/html,<img src=\"$1\"><h1>$2</h1><style>h1{color:$5;}img{z-index:-1;position:absolute;top:0;left:0;width:100%;height:100%;}</style><script>/*Generated By Trollgen*/setTimeout(()=>{window.location.href=\"$3\";},$4)</script>";
            richTextBox1.Text = template
                .Replace("$1", textBox1.Text)
                .Replace("$2", textBox2.Text)
                .Replace("$3", textBox3.Text)
                .Replace("$4", textBox4.Text)
                .Replace("$5", textBox5.Text);
        }

        private void textBox2_TextChanged(object sender, EventArgs e)
        {
           label1.Text = textBox2.Text;
            UpdTxt();
        }

        private void textBox4_TextChanged(object sender, EventArgs e)
        {
            UpdTxt();
        }

        private void textBox5_TextChanged(object sender, EventArgs e)
        {
            UpdTxt();
        }

        ListViewItem wanted;

        private void listView1_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (listView1.SelectedItems.Count == 0) return;
            wanted = listView1.SelectedItems[0];
        }

        private void button1_Click(object sender, EventArgs e)
        {
            textBox3.Text = "https://youtube.com";
            textBox4.Text = "500";
            switch (wanted.Text)
            {
                case "SamHydeBag":
                    textBox1.Text = "https://api.wagnerrobotics.club/sam.jpg";
                    textBox2.Text = "Hacked by Sam Hyde Bag!";
                    textBox5.Text = "black";
                    break;
                case "Shoebill Stork":
                    textBox1.Text = "https://realmafricasafaris.com/wp-content/uploads/2020/02/The-Shoebill-Stork.jpg";
                    textBox2.Text = "Hacked by Shoebill Stork!";
                    textBox5.Text = "white";
                    break;
            }
            UpdTxt();
        }

        private void textBox3_TextChanged(object sender, EventArgs e)
        {
            UpdTxt();
        }
    }
}
